# Generated by Django 6.0.3 on 2026-04-05 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefijo', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'SEDE_SERVICIOS',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('cod_sede', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SEDES',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('cod_servicio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SERVICIOS',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('sede_servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='turnero.sedeservicio')),
                ('tiempo_promedio_atencion_min', models.IntegerField(default=30)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('tiempo_espera_actual_min', models.IntegerField(default=0)),
                ('ultima_actualizacion_cache', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CONFIGURACIONES',
            },
        ),
        migrations.AddField(
            model_name='sedeservicio',
            name='sede',
            field=models.ForeignKey(db_column='cod_sede', on_delete=django.db.models.deletion.CASCADE, to='turnero.sede'),
        ),
        migrations.AddField(
            model_name='sedeservicio',
            name='servicio',
            field=models.ForeignKey(db_column='cod_servicio', on_delete=django.db.models.deletion.CASCADE, to='turnero.servicio'),
        ),
        migrations.CreateModel(
            name='Ventanilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cod_ventanilla', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(db_column='cod_sede', on_delete=django.db.models.deletion.CASCADE, to='turnero.sede')),
            ],
            options={
                'db_table': 'VENTANILLAS',
                'unique_together': {('sede', 'cod_ventanilla')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField()),
                ('consecutivo_diario', models.IntegerField()),
                ('codigo_visual', models.CharField(max_length=10)),
                ('estado', models.CharField(default='en_espera', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_atencion', models.DateTimeField(blank=True, null=True)),
                ('alerta_cercania_enviada', models.BooleanField(default=False)),
                ('ultima_notificacion_enviada', models.DateTimeField(blank=True, null=True)),
                ('operador', models.ForeignKey(blank=True, db_column='num_documento_operador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_operador', to=settings.AUTH_USER_MODEL)),
                ('sede_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnero.sedeservicio')),
                ('usuario', models.ForeignKey(blank=True, db_column='num_documento_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_paciente', to=settings.AUTH_USER_MODEL)),
                ('ventanilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnero.ventanilla')),
            ],
            options={
                'db_table': 'TURNOS',
                'unique_together': {('sede_servicio', 'fecha_turno', 'consecutivo_diario')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sedeservicio',
            unique_together={('sede', 'servicio')},
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='num_documento', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TOKENS_RECUPERACION',
                'unique_together': {('usuario', 'token_hash')},
            },
        ),
        migrations.CreateModel(
            name='QrToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_qr', models.CharField(max_length=128)),
                ('fecha_expira', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.turno')),
            ],
            options={
                'db_table': 'QR_TOKENS',
                'unique_together': {('turno', 'token_qr')},
            },
        ),
        migrations.CreateModel(
            name='HistorialEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('tipo_evento', models.CharField(max_length=20)),
                ('usuario_accion', models.ForeignKey(blank=True, db_column='num_documento_accion', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.turno')),
            ],
            options={
                'db_table': 'HISTORIAL_EVENTOS',
                'unique_together': {('turno', 'fecha_hora_evento')},
            },
        ),
    ]
