# Generated by Django 6.0.3 on 2026-04-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora_cita',
            field=models.TimeField(blank=True, help_text='Franja horaria de la consulta (intervalos de 15 min).', null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200),
        ),
    ]
