# Generated by Django 6.0.3 on 2026-05-13 00:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0002_turno_hora_cita_alter_sede_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeFarmacia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SEDES_FARMACIA',
            },
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo_servicio',
            field=models.CharField(choices=[('MEDICINA', 'Medicina'), ('LABORATORIO', 'Laboratorio'), ('VACUNACION', 'Vacunación'), ('FARMACIA', 'Farmacia')], default='MEDICINA', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='sede_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turnero.sedeservicio'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sede_farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnero.sedefarmacia'),
        ),
        migrations.CreateModel(
            name='TokenQRFarmacia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('sede_farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_qr', to='turnero.sedefarmacia')),
            ],
            options={
                'db_table': 'TOKENS_QR_FARMACIA',
            },
        ),
    ]
