# Generated by Django 6.0.3 on 2026-05-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0003_sedefarmacia_alter_turno_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sedefarmacia',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='sedefarmacia',
            name='longitud',
        ),
    ]
