# Generated by Django 6.0.3 on 2026-05-13 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0004_remove_sedefarmacia_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=15)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('numero_radicado', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('radicado', 'Radicado'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='radicado', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(blank=True, help_text='Sede donde ocurrió el evento (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnero.sede')),
                ('usuario', models.ForeignKey(db_column='num_documento_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to=settings.AUTH_USER_MODEL, to_field='num_documento')),
            ],
            options={
                'db_table': 'PQRS',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
