# Generated by Django 6.0.3 on 2026-05-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0005_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('MEDICINA', 'Medicina'), ('LABORATORIO', 'Laboratorio'), ('VACUNACION', 'Vacunación')], default='MEDICINA', help_text='Categoría a la que pertenece el servicio.', max_length=15),
        ),
    ]
